name: test_docker_access
on: push
jobs:
    display:
        runs-on: self-hosted
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
            - run: |
                docker build . -t masterdevopstools/web
                docker run -d -p 8000:5000 masterdevopstools/web
                docker ps
